cloudflare_api_token: ENC[AES256_GCM,data:ZnNeR2+8/8ot6Wjw+crAgSuj9SDbHR5dNITg/SdNTAw=,iv:Vmb0VSRDIVTYgxw25FfGsVy0C5ZbdTgBZCT2LliHO1I=,tag:g/jcm7RHUMcZo0ONdZeu8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwU0lDZno5UGhYYmJ0eEl5
            VHBuNlpONG5zZ3RiTmVnSHNYdytyeGhFaTNVCkYxYjV1U05BRGlwbXJJdkZXN054
            L2FLOG9mMVVtOU1wVmMwZmphYXRPajQKLS0tIHA0aXhrWlJhOWZGclk0anNhMGZE
            QUVjRkJVMUtVU2YvaStRVTBtMlhQa2cKUdYj47LuPwvo5d1KNK/VMtpgYyJLvnM0
            Y5Z4M1+y8aDe5Q8GIF7D8j/aN8FNFxZa271u1Q7Y9CsZ1qtTuXCJAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fucsvstpr082zemctfpjn2xkwq86thvlzan4tp9fyvg2q0rnnemshw690m
    lastmodified: "2026-10-04T15:32:27Z"
    mac: ENC[AES256_GCM,data:EWRPAZc2ZYAMWPNpklvAQ2zML2VNdAvfk1djnmxGpPjG1yKMLG3qUbckwsnX1Ky/OxNwu5GHN3kV5pb7VWyzQs5DTQ/fbpjGEDSl8GvFIdMK0Qz2VD0HcwYtOZNGhfVNQwaHK4/LMaUr0guPCjgsRzUiihyXXAMiYqbpKl8d3ac=,iv:Tu2W25d/Uksy5g0lWbILKkbdxCCp6+KKteNugKmcQ9A=,tag:1THvrxN4R3RLrbnyHGTm6g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
