cloudflare_api_token: ENC[AES256_GCM,data:WcThga4QZRV5zykWiBH6cGy4iSERyz1/zuq8P/1TeVSwkJf/xyvPYmeNdi86N8JT+6VaBB4=,iv:4vUclWIxvzK6qt4B5Y/aAegB6uWKmNk1f22GJ3Cp8As=,tag:78tQgIQmSJVqAxqHzAN4Bw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUL1l1dFFLSURrVzVIZWp2
            MCtqYlgvUlhtcllWZzl2UmNmdDlRRGFYWjBjCm43OWhXZVNTNDRBbTRBTU9Pd2Ju
            ektnTjVVZWwvb2VCTmFrM2pycjJSZ3MKLS0tIERzQzlPM1VFSkttajd4QzJzTzZX
            VjAzK0RGTW14VUs2U1owRGJCbUMzR00KujeI+BQj74qMGl/BD9EayJyye3j0Yv5h
            +usgAEddbGALQP/btitoPwNqPupkZ016XWqDHYNm2uKbK0Ya776Odw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fucsvstpr082zemctfpjn2xkwq86thvlzan4tp9fyvg2q0rnnemshw690m
    lastmodified: "2026-10-05T15:55:49Z"
    mac: ENC[AES256_GCM,data:FiVvvvtaJfBXcem6iVwVKwLpDwn5nrFrXzkE9LVFIteh17bS3FSLE7yTv1mCE+ao04JOA5Y6PF3DQVmciVBVEx9gqB+O3QF67UIWub+OWMEy6OpVs++CjEUtR3cac4ujR98cEMFAuUZ1wt+rJSgDeVnblFPK84Quag38JzlO0QE=,iv:Wq0G7cge8b/RGwo8uNoJFc7tgebDZyEvk7MoYOJWMB8=,tag:VPnkzGbf06f2mTGm1HHaWA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
