pihole_webpassword: ENC[AES256_GCM,data:oh4hbkEeYjGPn4Q=,iv:tnyC7vuFgklSabsxfCK1HC78Geod/9dC6HNBShkFKak=,tag:dJ1HACckqYPBkiPyklbpBQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsR0lGQm9WT3M3VHVMNFhG
            em5XTXVkUEVUcWxRS0pTcER6eGlCR0JKbmtzCkZ6ZUMxYTMyTk5KcEkyTU85TkhF
            L2Z2eGRtd1g1ekp4bkpuRHlnQ2pVNEEKLS0tIEViVm5FU2lyVStXSzhabHRiYjdw
            UHRWRjZ2ekxhU0pSeXFDSjlSYWNmQjgKY0yLMqpylYbi9bOOjYpoROWy4s4Q5wrg
            3BGeUz/F9dt4CX8rllZB0zzI2NRAtBULgtp0VDDeoRyx6gT4N7gF7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fucsvstpr082zemctfpjn2xkwq86thvlzan4tp9fyvg2q0rnnemshw690m
    lastmodified: "2026-10-05T15:59:22Z"
    mac: ENC[AES256_GCM,data:D3UBrU1l/jnovnoRZA41TucBGPj9paXYgrYbqqqs7txChvwUA9n8V2LWG6XME/cSlza8bbdMOnih4PR2pp3tS5R3u2oj2gMKf+gWMdqxi84U7EPHaeoKJatd/eBD0X3Sz0kuuL4bJnuLoaP1pRISNp/MvBYLB44MGsh/8N9r2xU=,iv:UqsLFmrk2PT5m39nbQPtwo4pGgPVRX3RI5fFoMTz8Rk=,tag:j90vwvYOItWPF5Dpqv709w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
