galaxy_info:
  author: Bruno Cochofel
  description: Create the shared Docker macvlan network CoreDNS and Pihole attach to
  license: MIT
  min_ansible_version: "2.15"
  galaxy_tags: []
dependencies: []
