galaxy_info:
  author: Bruno Cochofel
  description: Run CoreDNS as a Docker Compose service on the shared dns macvlan network
  license: MIT
  min_ansible_version: "2.15"
  galaxy_tags: []
dependencies: []
