galaxy_info:
  author: Bruno Cochofel
  description: Enroll the template's Elastic Agent into homelab-proxmox-workloads' Fleet
  license: MIT
  min_ansible_version: "2.15"
  galaxy_tags: []
dependencies: []
